### ISSUE TITLE
TypeError: int() argument

### ISSUE THREAD

**Issue by mhmdrzkii** [raveen2k3/ZeroTwo#3]
sir i tried it and 

Traceback (most recent call last):
  File "c:\Users\rizkirdp\ZeroTwo\zerotwo.py", line 10, in <module>
    import configs
  File "c:\Users\rizkirdp\ZeroTwo\configs.py", line 9, in <module>
    API_ID = int(os.getenv("13937340"))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

how to fix?

**Comment by raveen2k3** [comment]
Will try to fix it  tmrw :-)

**Comment by mhmdrzkii** [comment]
thank you sir, i'm waiting for that goodluck

**Comment by mhmdrzkii** [comment]
and some filters also seem to have errors for some reason, like 

> /ban `'NoneType' object has no attribute 'message_id'`

> /promote `'NoneType' object has no attribute 'message_id'`

**Comment by ghost** [comment]
@mhmdrzkii message_id became id. Replace it.

**Comment by mhmdrzkii** [comment]
@rozari0 how about, 

Traceback (most recent call last):
File "c:\Users\rizkirdp\ZeroTwo\zerotwo.py", line 10, in
import configs
File "c:\Users\rizkirdp\ZeroTwo\configs.py", line 9, in
API_ID = int(os.getenv("13937340"))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by mhmdrzkii** [comment]
i use in vscode

**Comment by ghost** [comment]
@mhmdrzkii API_ID = 13937340

**Comment by mhmdrzkii** [comment]
same,

```
raise AttributeError("No API Key found. More info: https://docs.pyrogram.org/intro/setup")
AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup
PS C:\Users\rizkirdp\ZeroTwo>
```

**Comment by mhmdrzkii** [comment]
i think it's right 

```
API_ID = 13937340
API_HASH = os.getenv("823650e1894861c0d812c0bxxxx")
BOT_TOKEN = os.getenv("55694xxxx"
```

**Comment by ghost** [comment]
@mhmdrzkii Remove os.getenv(blahblahblah)

Just declare variable with value.

**Comment by TAMILVIP007** [comment]
@mhmdrzkii Sleep

**Comment by TAMILVIP007** [comment]
@TAMILVIP007 Shu

**Comment by TAMILVIP007** [comment]
@TAMILVIP007 Fu

**Comment by STBxD** [comment]
@TAMILVIP007 lol

**Comment by IndrajeethY** [comment]
@STBxD Nou

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Stfu

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Fu

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Mf

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Gay

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Shit

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Slut

**Comment by IndrajeethY** [comment]
@TAMILVIP007 .

**Comment by IndrajeethY** [comment]
@TAMILVIP007 .

**Comment by IndrajeethY** [comment]
@TAMILVIP007 .

**Comment by IndrajeethY** [comment]
@TAMILVIP007 .

**Comment by IndrajeethY** [comment]
@TAMILVIP007 .

**Comment by IndrajeethY** [comment]
@TAMILVIP007 .

**Comment by IndrajeethY** [comment]
@TAMILVIP007 .
